# Baseline

In [53]:
import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split, cross_validate, StratifiedGroupKFold, KFold

In [54]:
!pip freeze | grep "numpy\|pandas\|lightgbm\|scikit-learn"

lightgbm==4.3.0
numpy @ file:///C:/b/abs_c1ywpu18ar/croot/numpy_and_numpy_base_1708638681471/work/dist/numpy-1.26.4-cp311-cp311-win_amd64.whl#sha256=5dfd3e04dc1c2826d3f404fdc7f93c097901f5da9b91f4f394f79d4e038ed81d
numpydoc @ file:///C:/ci_311/numpydoc_1676453412027/work
pandas @ file:///C:/b/abs_fej9bi0gew/croot/pandas_1702318041921/work/dist/pandas-2.1.4-cp311-cp311-win_amd64.whl#sha256=d3609b7cc3e3c4d99ad640a4b8e710ba93ccf967ab8e5245b91033e0200f9286
scikit-learn @ file:///C:/b/abs_38k7ridbgr/croot/scikit-learn_1684954723009/work


## Загрузка данных

In [55]:
train_df = pd.read_parquet("train_data.pqt")
test_df = pd.read_parquet("test_data.pqt")

In [56]:
train_df.head(30)

id     date  balance_amt_avg  balance_amt_max  balance_amt_min  \
0    0  month_1         0.744845         0.705492         1.287207   
1    0  month_2         1.049605         0.831916         2.458609   
2    0  month_3         0.692653         0.740253         0.430042   
3    1  month_1        -0.081586        -0.091860        -0.114040   
4    1  month_2        -0.094962        -0.100504        -0.119302   
5    1  month_3        -0.090605        -0.114275        -0.114119   
6    2  month_1        -0.154685        -0.186795        -0.122805   
7    2  month_2        -0.152784        -0.193686        -0.122805   
8    2  month_3        -0.148737        -0.187003        -0.112416   
9    3  month_1        -0.156643        -0.204861        -0.125660   
10   3  month_2        -0.156666        -0.204790        -0.125995   
11   3  month_3        -0.156522        -0.204718        -0.125759   
12   4  month_1        -0.138847        -0.182486        -0.125630   
13   4  month_2        -0.129233        -0.162965        -0.108713   
14   4  month_3        -0.141798        -0.170262        -0.125672   
15   5  month_1              NaN              NaN              NaN   
16   5  month_2              NaN              NaN              NaN   
17   5  month_3              NaN              NaN              NaN   
18   6  month_1        -0.012978         0.167324        -0.105271   
19   6  month_2         0.166101         0.166826         0.102481   
20   6  month_3        -0.126878        -0.116844        -0.124882   
21   7  month_1        -0.156437        -0.204698        -0.125176   
22   7  month_2        -0.156426        -0.204698        -0.125119   
23   7  month_3        -0.156215        -0.204464        -0.125995   
24   8  month_1        -0.146542        -0.193037        -0.121922   
25   8  month_2        -0.143509        -0.187596        -0.125143   
26   8  month_3        -0.152684        -0.197020        -0.125995   
27   9  month_1        -0.156411        -0.204687        -0.125084   
28   9  month_2        -0.156411        -0.204687        -0.125084   
29   9  month_3        -0.156411        -0.204687        -0.125084   

    balance_amt_day_avg     channel_code       city      city_type  \
0              0.748101   channel_code_5    city_23    city_type_0   
1              1.053805   channel_code_5    city_23    city_type_0   
2              0.695747   channel_code_5    city_23    city_type_0   
3             -0.080890   channel_code_2    city_14    city_type_0   
4             -0.094307   channel_code_2    city_14    city_type_0   
5             -0.089937   channel_code_2    city_14    city_type_0   
6             -0.154215  channel_code_12   city_613  city_type_306   
7             -0.152308  channel_code_12   city_613  city_type_306   
8             -0.148249  channel_code_12   city_613  city_type_306   
9             -0.156179  channel_code_14    city_21    city_type_0   
10            -0.156202  channel_code_14    city_21    city_type_0   
11            -0.156058  channel_code_14    city_21    city_type_0   
12            -0.138328   channel_code_8    city_21    city_type_0   
13            -0.128684   channel_code_8    city_21    city_type_0   
14            -0.141289   channel_code_8    city_21    city_type_0   
15                  NaN             None       None           None   
16                  NaN             None       None           None   
17                  NaN  channel_code_21       None           None   
18            -0.012069   channel_code_5    city_25    city_type_0   
19             0.167564   channel_code_5    city_25    city_type_0   
20            -0.126322   channel_code_5    city_25    city_type_0   
21            -0.155972  channel_code_31    city_39    city_type_0   
22            -0.155961  channel_code_31    city_39    city_type_0   
23            -0.155954  channel_code_31    city_39    city_type_0   
24            -0.146047   channel_code_8    city_65    city_type_0   
25           

In [57]:
test_df.head(3)

id     date  balance_amt_avg  balance_amt_max  balance_amt_min  \
0  200000  month_4        -0.096224         0.335496        -0.125995   
1  200000  month_5        -0.024255        -0.059806        -0.124295   
2  200000  month_6         0.045988         0.049418        -0.125995   

   balance_amt_day_avg     channel_code     city    city_type index_city_code  \
0            -0.095578  channel_code_12  city_14  city_type_0            None   
1            -0.023381  channel_code_12  city_14  city_type_0            None   
2             0.047079  channel_code_12  city_14  city_type_0            None   

   ...  sum_cred_g_oper_3m  cnt_cred_g_oper_3m cnt_days_cred_g_oper_3m  \
0  ...            0.010952            0.946066                0.407762   
1  ...            0.006812            0.945281                0.396267   
2  ...            0.006812            0.945281                0.396267   

  sum_deb_h_oper_3m  cnt_deb_h_oper_3m  cnt_days_deb_h_oper_3m  \
0         -0.153950           0.548895                0.541020   
1         -0.150505           0.549468                0.552131   
2         -0.152800           0.549468                0.541020   

   sum_cred_h_oper_3m  cnt_cred_h_oper_3m cnt_days_cred_h_oper_3m  \
0            0.031742            0.257278                0.561353   
1            0.237817            0.264211                0.715199   
2            0.387566            0.268543                0.836079   

  start_cluster  
0           {α}  
1           {α}  
2          None  

[3 rows x 92 columns]

In [58]:
cat_cols = [
    "channel_code", "city", "city_type",
    "okved", "segment", "start_cluster",
    "index_city_code", "ogrn_month", "ogrn_year",
]

Обозначение категориальных признаков

In [59]:
train_df[cat_cols] = train_df[cat_cols].astype("category")
test_df[cat_cols] = test_df[cat_cols].astype("category")

Создаем выборки для валидации и обучения

In [60]:
X = train_df.drop(["id", "date", "end_cluster"], axis=1)
y = train_df["end_cluster"]

x_train, x_val, y_train, y_val = train_test_split(X, y,
                                                  test_size=0.2,
                                                  random_state=42)

## Обучение модели

В качестве базовой модели возьмем LGBM обучим на всех признаках

In [61]:
params = {
    "boosting_type": "gbdt",
    "objective": "multiclass",
    "metric": "auc_mu",
    "max_depth": 10,
    "num_leaves": 20,
    "min_data_in_leaf": 10,
    "learning_rate": 0.01,
    "feature_fraction": 0.7,
    "bagging_fraction": 0.7,
    "bagging_freq": 5,
    "n_estimators": 100,
    "min_data_in_bin": 1,
    "max_bin": 64,
    "verbose": -1,
    "random_state": 42,
    "n_jobs": -1
}



In [62]:
from sklearn.model_selection import StratifiedKFold, LeavePOut, LeaveOneOut, ShuffleSplit

model = LGBMClassifier(**params)


# cv = KFold(n_splits=3)
cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=42)
auc_scores = []  # Список для хранения показателей AUC для каждого разбиения


In [63]:
def weighted_roc_auc(y_true, y_pred, labels, weights_dict):
    unnorm_weights = np.array([weights_dict[label] for label in labels])
    weights = unnorm_weights / unnorm_weights.sum()
    classes_roc_auc = roc_auc_score(y_true, y_pred, labels=labels,
                                    multi_class="ovr", average=None)
    return sum(weights * classes_roc_auc)

In [64]:
cluster_weights = pd.read_excel("cluster_weights.xlsx").set_index("cluster")
weights_dict = cluster_weights["unnorm_weight"].to_dict()

In [77]:

from sklearn.model_selection import RepeatedStratifiedKFold

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=4, random_state=12)
for train_idx, val_idx in cv.split(X, y):
    print(train_idx)

[     0      1      2 ... 599996 599997 599998]
[     0      1      2 ... 599992 599997 599999]
[     0      1      2 ... 599996 599998 599999]
[     0      3      4 ... 599997 599998 599999]
[     1      2      4 ... 599997 599998 599999]
[     0      1      2 ... 599997 599998 599999]
[     2      3      4 ... 599996 599997 599998]
[     0      1      2 ... 599997 599998 599999]
[     0      1      2 ... 599994 599996 599999]
[     0      1      3 ... 599997 599998 599999]
[     0      1      3 ... 599997 599998 599999]
[     0      1      2 ... 599996 599997 599999]
[     0      1      2 ... 599994 599997 599998]
[     0      2      3 ... 599996 599998 599999]
[     1      2      3 ... 599997 599998 599999]
[     0      1      2 ... 599997 599998 599999]
[     2      3      4 ... 599997 599998 599999]
[     0      1      3 ... 599996 599997 599998]
[     0      1      2 ... 599997 599998 599999]
[     0      1      2 ... 599994 599996 599999]


In [65]:

for train_idx, val_idx in cv.split(X, y):
    x_train, x_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model.fit(x_train, y_train)

    y_pred_proba = model.predict_proba(x_val)

    auc_score = weighted_roc_auc(y_val, y_pred_proba, model.classes_, weights_dict)
    auc_scores.append(auc_score)

mean_auc = np.mean(auc_scores)
std_auc = np.std(auc_scores)
print(f"Средний взвешенный ROC AUC: {mean_auc:.3f} ± {std_auc:.3f}")

Средний взвешенный ROC AUC: 0.907 ± 0.008
